from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from pathlib import Path
from typing import Any

from client.plugins.base import PluginBase

logger = logging.getLogger(__name__)

SB_HEADER = """// SilverBullet v1.1 Script
// Generated by Beta Browser AI
// Run with: sb run <file.svb>
"""

SB_TEMPLATES = {
    "scrape": """// SilverBullet v1.1 - Web Scraper
// @target URL to scrape
// @selector CSS selector for data

open "{{target}}"
wait 2000
const data = queryAll("{{selector}}")
const results = data.map(el => ({
  text: el.textContent.trim(),
  href: el.getAttribute("href") || "",
  html: el.outerHTML
}))
output(JSON.stringify(results, null, 2))
""",
    "login": """// SilverBullet v1.1 - Auto Login
// @target Login URL
// @username Username
// @password Password

open "{{target}}"
wait 2000
const user = query("input[type=text], input[type=email], input[name=username]")
if (user) {
  type(user, "{{username}}")
}
const pass = query("input[type=password]")
if (pass) {
  type(pass, "{{password}}")
}
const btn = query("button[type=submit], input[type=submit]")
if (btn) click(btn)
wait 3000
output("Login attempted: " + location.href)
""",
    "fill_form": """// SilverBullet v1.1 - Form Filler
// @target Form URL
// @fields JSON object of field values

open "{{target}}"
wait 2000
const fields = JSON.parse('{{fields}}')
for (const [selector, value] of Object.entries(fields)) {
  const el = query(selector)
  if (el) {
    type(el, value)
  }
}
const submit = query("button[type=submit], input[type=submit]")
if (submit) click(submit)
wait 2000
output("Form submitted")
""",
    "screenshot": """// SilverBullet v1.1 - Screenshot
// @target URL to screenshot

open "{{target}}"
wait 3000
const img = screenshot()
output("Screenshot saved: " + img)
""",
    "monitor": """// SilverBullet v1.1 - Page Monitor
// @target URL to monitor
// @interval Check interval in ms
// @selector Element to watch

setInterval(() => {
  const el = query("{{selector}}")
  if (el) {
    output(JSON.stringify({
      text: el.textContent.trim(),
      html: el.innerHTML,
      timestamp: Date.now()
    }))
  }
}}, {{interval}} || 5000)
open "{{target}}")
""",
    "data_extract": """// SilverBullet v1.1 - Data Extractor
// @target URL
// @rules Extraction rules as JSON

open "{{target}}"
wait 3000
const rules = JSON.parse('{{rules}}')
const result = {}
for (const [key, selector] of Object.entries(rules)) {
  const el = query(selector)
  result[key] = el ? el.textContent.trim() : null
}
output(JSON.stringify(result, null, 2))
""",
    "multistep": """// SilverBullet v1.1 - Multi-step Workflow
// @steps Array of step objects

const steps = JSON.parse('{{steps}}')
for (const step of steps) {
  output("Step: " + step.name)
  if (step.url) open(step.url)
  if (step.wait) await sleep(step.wait)
  if (step.selector && step.value) {
    const el = query(step.selector)
    if (el) type(el, step.value)
  }
  if (step.click) {
    const el = query(step.click)
    if (el) click(el)
  }
  if (step.screenshot) screenshot()
  if (step.output) output(step.output)
}
output("Workflow complete")
""",
    "api_call": """// SilverBullet v1.1 - API Caller
// @method HTTP method
// @url API endpoint
// @body Request body (JSON)

const response = await fetch("{{url}}", {
  method: "{{method}}" || "GET",
  headers: {"Content-Type": "application/json"},
  body: "{{body}}" ? JSON.parse('{{body}}') : undefined
})
const data = await response.json()
output(JSON.stringify(data, null, 2))
""",
}


class Plugin(PluginBase):
    name = "silverbullet"
    description = "SilverBullet v1.1 .svb script creator, editor, runner, templates"
    version = "1.0.0"
    author = "Beta"

    def __init__(self, config: Any = None) -> None:
        super().__init__(config)
        self._scripts_dir = Path(os.environ.get("SB_SCRIPTS_DIR", "./silverbullet_scripts"))
        self._scripts_dir.mkdir(parents=True, exist_ok=True)

    async def execute(self, action: str = "list", **kw: Any) -> dict[str, Any]:
        actions = {
            "create": self._create, "run": self._run, "edit": self._edit,
            "list": self._list, "delete": self._delete, "info": self._info,
            "template": self._template, "templates_list": self._templates_list,
            "from_description": self._from_desc, "validate": self._validate,
            "convert_from_js": self._convert_js, "package": self._package,
        }
        fn = actions.get(action)
        if not fn:
            return {"error": f"Unknown action: {action}", "available": list(actions.keys())}
        return await fn(**kw)

    async def _create(self, name: str = "", code: str = "", description: str = "", **kw: Any) -> dict:
        if not name:
            return {"error": "name required"}
        if not name.endswith(".svb"):
            name += ".svb"

        script = SB_HEADER + f"// {description}\n\n" if description else SB_HEADER + "\n"
        script += code

        path = self._scripts_dir / name
        path.write_text(script, encoding="utf-8")
        return {"path": str(path), "name": name, "lines": script.count("\n") + 1, "size": len(script)}

    async def _run(self, name: str = "", **kw: Any) -> dict:
        if not name:
            return {"error": "name required"}
        path = self._scripts_dir / name
        if not path.exists():
            return {"error": f"Script not found: {name}"}

        code = path.read_text(encoding="utf-8")
        output_lines = []
        errors = []

        try:
            lines = code.strip().split("\n")
            parsed_steps = []
            vars_dict = {}

            for line in lines:
                line = line.strip()
                if not line or line.startswith("//"):
                    continue

                if line.startswith("open "):
                    url = line[5:].strip().strip('"').strip("'")
                    parsed_steps.append({"action": "navigate", "url": url})
                elif line.startswith("wait "):
                    ms = line[5:].strip()
                    parsed_steps.append({"action": "wait", "ms": int(ms) if ms.isdigit() else 1000})
                elif "query(" in line:
                    parsed_steps.append({"action": "query", "raw": line})
                elif "queryAll(" in line:
                    parsed_steps.append({"action": "query_all", "raw": line})
                elif "type(" in line:
                    parsed_steps.append({"action": "type", "raw": line})
                elif "click(" in line:
                    parsed_steps.append({"action": "click", "raw": line})
                elif "screenshot()" in line:
                    parsed_steps.append({"action": "screenshot"})
                elif "output(" in line:
                    msg = line[line.index("output(") + 7:].rstrip(")").strip().strip('"').strip("'")
                    parsed_steps.append({"action": "output", "message": msg})
                elif line.startswith("const ") or line.startswith("var "):
                    parsed_steps.append({"action": "variable", "raw": line})

            return {
                "script": name,
                "steps_parsed": len(parsed_steps),
                "steps": parsed_steps,
                "note": "Script parsed. Send steps to browser worker for execution.",
                "output_preview": output_lines,
                "errors": errors,
            }
        except Exception as e:
            return {"error": str(e), "script": name}

    async def _edit(self, name: str = "", code: str = "", append: bool = False, **kw: Any) -> dict:
        if not name:
            return {"error": "name required"}
        path = self._scripts_dir / name
        if not path.exists():
            return {"error": f"Script not found: {name}"}

        if append:
            current = path.read_text(encoding="utf-8")
            path.write_text(current + "\n" + code, encoding="utf-8")
        else:
            path.write_text(code, encoding="utf-8")

        content = path.read_text(encoding="utf-8")
        return {"path": str(path), "lines": content.count("\n") + 1, "size": len(content)}

    async def _list(self, **kw: Any) -> dict:
        scripts = []
        for f in sorted(self._scripts_dir.glob("*.svb")):
            content = f.read_text(encoding="utf-8")
            desc = ""
            for line in content.split("\n")[:5]:
                if line.strip().startswith("//"):
                    desc = line.strip().lstrip("/").strip()
                    break
            scripts.append({
                "name": f.name, "size": f.stat().st_size,
                "lines": content.count("\n") + 1, "description": desc,
                "modified": f.stat().st_mtime,
            })
        return {"scripts": scripts, "count": len(scripts), "dir": str(self._scripts_dir)}

    async def _delete(self, name: str = "", **kw: Any) -> dict:
        path = self._scripts_dir / name
        if path.exists():
            path.unlink()
            return {"deleted": name}
        return {"error": f"Script not found: {name}"}

    async def _info(self, name: str = "", **kw: Any) -> dict:
        path = self._scripts_dir / name
        if not path.exists():
            return {"error": f"Script not found: {name}"}
        content = path.read_text(encoding="utf-8")
        comments = [l.strip().lstrip("/").strip() for l in content.split("\n") if l.strip().startswith("//")]
        return {
            "name": name, "size": path.stat().st_size,
            "lines": content.count("\n") + 1, "header_comments": comments[:10],
            "content": content[:5000],
        }

    async def _template(self, name: str = "", params: dict | None = None, **kw: Any) -> dict:
        tpl = SB_TEMPLATES.get(name)
        if not tpl:
            return {"error": f"Template '{name}' not found", "available": list(SB_TEMPLATES.keys())}

        code = tpl
        if params:
            for k, v in params.items():
                code = code.replace("{{" + k + "}}", str(v))

        return {"template": name, "code": code, "params_used": list(params.keys()) if params else []}

    async def _templates_list(self, **kw: Any) -> dict:
        templates = []
        for name, code in SB_TEMPLATES.items():
            desc = ""
            for line in code.split("\n")[:3]:
                if line.strip().startswith("//"):
                    desc = line.strip().lstrip("/").strip()
                    break
            templates.append({"name": name, "description": desc, "lines": code.count("\n") + 1})
        return {"templates": templates, "count": len(templates)}

    async def _from_desc(self, description: str = "", name: str = "", **kw: Any) -> dict:
        if not description:
            return {"error": "description required"}

        system = (
            "Generate a SilverBullet v1.1 script (.svb) for this task.\n"
            "SilverBullet commands: open(url), wait(ms), query(selector), queryAll(selector), "
            "type(element, text), click(element), screenshot(), output(msg), sleep(ms)\n"
            "Use JavaScript-like syntax. Add // @param comments for configurable values.\n"
            "Start with: // SilverBullet v1.1 Script\n"
            "Output ONLY the script code, no explanation."
        )

        from client.plugins.base import PluginBase
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                api_key = os.environ.get("AI_API_KEY", "")
                base_url = os.environ.get("AI_BASE_URL", "https://api.groq.com/openai/v1")
                model = os.environ.get("AI_MODEL", "openai/gpt-oss-120b")
                r = await client.post(
                    f"{base_url}/chat/completions",
                    headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                    json={"model": model, "messages": [
                        {"role": "system", "content": system},
                        {"role": "user", "content": description},
                    ], "temperature": 0.3, "max_tokens": 2048},
                )
                r.raise_for_status()
                code = r.json()["choices"][0]["message"]["content"]
        except Exception as e:
            code = f'// Generated script for: {description}\n// Error generating: {e}\nopen "about:blank"\noutput("Script generation failed")'

        if name:
            if not name.endswith(".svb"):
                name += ".svb"
            path = self._scripts_dir / name
            path.write_text(code, encoding="utf-8")
            return {"name": name, "code": code, "saved": str(path)}

        return {"code": code}

    async def _validate(self, name: str = "", **kw: Any) -> dict:
        path = self._scripts_dir / name
        if not path.exists():
            return {"error": f"Script not found: {name}"}

        content = path.read_text(encoding="utf-8")
        issues = []
        valid_commands = {"open", "wait", "query", "queryAll", "type", "click",
                          "screenshot", "output", "sleep", "setInterval", "fetch",
                          "const", "var", "let", "if", "for", "while", "return"}

        for i, line in enumerate(content.split("\n"), 1):
            stripped = line.strip()
            if not stripped or stripped.startswith("//"):
                continue
            first_word = stripped.split("(")[0].split("=")[0].split(" ")[-1].strip()
            if first_word and first_word not in valid_commands and not first_word.startswith(("{", "}", "[", "]", '"', "'")):
                if not any(stripped.startswith(k) for k in ["const ", "var ", "let ", "if ", "for ", "while ", "return "]):
                    issues.append({"line": i, "issue": f"Unknown command: {first_word}"})

        return {"script": name, "valid": len(issues) == 0, "issues": issues, "lines": content.count("\n") + 1}

    async def _convert_js(self, code: str = "", name: str = "", **kw: Any) -> dict:
        if not code:
            return {"error": "code required"}

        sb_code = SB_HEADER + "\n"
        for line in code.split("\n"):
            stripped = line.strip()
            if stripped.startswith("window.location"):
                url = stripped.split("=")[1].strip().rstrip(";").strip('"').strip("'")
                sb_code += f'open "{url}"\n'
            elif "document.querySelector" in stripped:
                sb_code += f"// {stripped}\n"
            elif stripped.startswith("//"):
                sb_code += stripped + "\n"
            else:
                sb_code += stripped + "\n"

        if name:
            if not name.endswith(".svb"):
                name += ".svb"
            path = self._scripts_dir / name
            path.write_text(sb_code, encoding="utf-8")
            return {"name": name, "code": sb_code, "saved": str(path)}

        return {"code": sb_code}

    async def _package(self, name: str = "", description: str = "", **kw: Any) -> dict:
        path = self._scripts_dir / name
        if not path.exists():
            return {"error": f"Script not found: {name}"}

        code = path.read_text(encoding="utf-8")
        package = {
            "name": name,
            "version": "1.0.0",
            "description": description or f"SilverBullet script: {name}",
            "author": "Beta Browser AI",
            "silverbullet_version": "1.1",
            "code": code,
            "created": time.strftime("%Y-%m-%dT%H:%M:%SZ"),
        }

        pkg_path = self._scripts_dir / f"{name}.json"
        pkg_path.write_text(json.dumps(package, indent=2))
        return {"package": str(pkg_path), "manifest": package}
